### PR TITLE
feat: Added new favicon

### PR DESCRIPTION
**Pull request by rameshchandra8520**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes: #65 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by diivi** [comment]
Please add a screenshot for visual changes too :)

**Comment by rameshchandra8520** [comment]
Hi @diivi, I am getting some errors while deploying to the browser after using `npm start`. Can you help me with where I am missing something?
(I followed the procedure mentioned in the Readme file)


```
Compiled with some errors in 1.37s

Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
client (webpack 5.61.0) compiled with 18 errors

```

**Comment by diivi** [comment]
I have faced this error too, it's probably because of a version mismatch.
Type this in your terminal and run the tests again.

`export NODE_OPTIONS=--openssl-legacy-provider`

To remove this setting, to make sure `git push` and other commands work, just reopen the terminal.

**Comment by 0-vortex** [comment]
> I have faced this error too, it's probably because of a version mismatch. Type this in your terminal and run the tests again.
> 
> `export NODE_OPTIONS=--openssl-legacy-provider`
> 
> To remove this setting, to make sure `git push` and other commands work, just reopen the terminal.

Don't do that, that is opening up your machine to some SSL security concern. Instead, wait for https://github.com/open-sauced/docs.opensauced.pizza/pull/74 to get merged and update from the main branch!

**Comment by diivi** [comment]
> > I have faced this error too, it's probably because of a version mismatch. Type this in your terminal and run the tests again.
> > `export NODE_OPTIONS=--openssl-legacy-provider`
> > To remove this setting, to make sure `git push` and other commands work, just reopen the terminal.
> 
> Don't do that, that is opening up your machine to some SSL security concern. Instead, wait for #74 to get merged and update from the main branch!

It's setting an env variable for the current shell session, I close the session right after. How is it a security issue then?

**Comment by 0-vortex** [comment]
> > > I have faced this error too, it's probably because of a version mismatch. Type this in your terminal and run the tests again.
> > > `export NODE_OPTIONS=--openssl-legacy-provider`
> > > To remove this setting, to make sure `git push` and other commands work, just reopen the terminal.
> > 
> > 
> > Don't do that, that is opening up your machine to some SSL security concern. Instead, wait for #74 to get merged and update from the main branch!
> 
> It's setting an env variable for the current shell session, I close the session right after. How is it a security issue then?

The SSL libs require patching inside the package-lock, because we are not using the fixed nodejs version in our workflows, it's enabling the propagation of the bug to our deploys, and anyone cloning the project 😅

**Pull request closed without merging**
