### PR TITLE
docs: add head metadata

### LINKED ISSUE #45: feature: add and customize head metadata
### Type of feature

📝 Documentation

### Current behavior

Current documentation does not contain head metadata.

https://docusaurus.io/docs/markdown-features/head-metadata

### Suggested solution

Add and customize head metadata to all markdown files.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by huynhicode**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds [head metadata](https://docusaurus.io/docs/markdown-features/head-metadata) to the markdown files. There are also some auto-linting fixes.

## Related Tickets & Documents

Resolves #45

## Mobile & Desktop Screenshots/Recordings

The head metadata does not affect any visual aspects of the documentation site.

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [x] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

None

## [optional] What gif best describes this PR or how it makes you feel?

https://media.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif

### CODE REVIEW

**Comment by mtfoley** [comment]
I updated the PR description to satisfy automation, and I approved first contributor actions run.

**Comment by huynhicode** [comment]
Thank you @mtfoley !

**Review by 0-vortex — APPROVED** [review]
LGTM! 👍 

Since we don't have a deploy preview for this, can any of the @open-sauced/triage team take a look? 🍕 ❤️

**Comment by NsdHSO** [comment]
LGTM! 🎉

**Pull request merged**
