### PR TITLE
feat: Update logo.svg Feature: Update Favicon to Pizza #80

### LINKED ISSUE #80: Feature: Update Favicon to Pizza
### Type of feature

🍕 Feature

### Current behavior
The favicon is not legible. 

Screen Shot 2023-05-05 at 6 44 30 AM

### Suggested solution
To solve this issue, you have to replace the current [docs.opensauced.pizza](https://docs.opensauced.pizza/) (the one on the left) favicon with the [hot.opensauced.pizza](https://hot.opensauced.pizza/) (the one on the right) favicon.

227435561-15c3b757-8b2a-49e5-a317-662152aff338

### Additional context

Previous issue #65 was meant to fix this and it didn't

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by MZHoffman**
Feature: Update Favicon to Pizza #80

Hello,

It's one of my first contributions so please be easy on me :)

Thanks!

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR replaces icon as per "Feature: Update Favicon to Pizza #80"

## Related Tickets & Documents

Fixes #80 
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Hi, thanks for the contribution. Can you add a screenshot to the description @MZHoffman?

**Comment by MZHoffman** [comment]
> Hi, thanks for the contribution. Can you add a screenshot to the description @MZHoffman?

The problem is I wasn't able to replicate the issue. So I have looked up what directly on webpage which file is responsible for favicon.

on [docs.opensauced.pizza](https://docs.opensauced.pizza/) this line is responsible for the favicon.

`<link rel="icon" href="/img/logo.svg">`

Now i can see its generated by docusaurus.config.js 

``` plugins: [
    [
      '@docusaurus/plugin-pwa',
      {
        debug: true,
        offlineModeActivationStrategies: [
          'appInstalled',
          'standalone',
          'queryString',
        ],
        pwaHead: [
          {
            tagName: 'link',
            rel: 'icon',
            href: '/img/logo.svg',
          },
          {
            tagName: 'link',
            rel: 'manifest',
            href: '/manifest.json', // your PWA manifest
          },
          {
            tagName: 'meta',
            name: 'theme-color',
            content: '#313d3e',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-capable',
            content: 'yes',
          },
          {
            tagName: 'meta',
            name: 'apple-mobile-web-app-status-bar-style',
            content: '#000',
          },
          {
            tagName: 'link',
            rel: 'apple-touch-icon',
            href: '/apple-touch-icon.png',
          },
          {
            tagName: 'link',
            rel: 'mask-icon',
            href: '/img/logo.svg',
            color: 'rgb(37, 194, 160)',
          },
          {
            tagName: 'meta',
            name: 'msapplication-TileImage',
            content: '/img/logo.svg',
          },
          {
            tagName: 'meta',
            name: 'msapplication-TileColor',
            content: '#000',
          },
        ],```

the problem is it looks ok when you run npm start so it has to happen after build and i'm not sure how to deploy app to check . Any help appreciated

**Comment by bdougie** [comment]
```
npm run build
npm run serve
```

@MZHoffman the above commands are what is needed to test locally, which I did on this PR and it looks fine to me.

**Comment by MZHoffman** [comment]
> ```
> npm run build
> npm run serve
> ```
> 
> @MZHoffman the above commands are what is needed to test locally, which I did on this PR and it looks fine to me.

Thank you. 

The logo.svg is used in different places. For instance footer so I wouldn't merge it. Sorry my bad

**Pull request merged**
